// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqE6JGiDy_Iz4T6V92OhQMuUYHnvP6zWw',
    appId: '1:565958456490:android:05f215b0500da333694cd3',
    messagingSenderId: '565958456490',
    projectId: 'yummy-1376d',
    storageBucket: 'yummy-1376d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_OB8NG1_TRzI2TFeBh0UxGyQ0UROt2Go',
    appId: '1:565958456490:ios:7b9e40851a085904694cd3',
    messagingSenderId: '565958456490',
    projectId: 'yummy-1376d',
    storageBucket: 'yummy-1376d.appspot.com',
    iosClientId: '565958456490-5l8pqt19vcjmj0laq3im4vnqd6teiuf3.apps.googleusercontent.com',
    iosBundleId: 'yummy.cornell.edu',
  );
}
